# Generated by Django 4.2.20 on 2025-04-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearskinextension',
            name='descripcion',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='invextension',
            name='descripcion',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='pveextension',
            name='descripcion',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='usecskinextension',
            name='descripcion',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], default='cliente', max_length=15),
        ),
        migrations.AlterField(
            model_name='version',
            name='caracteristicas',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='version',
            name='descripcion',
            field=models.TextField(blank='True', null='True'),
        ),
    ]
