# Generated by Django 4.2.20 on 2025-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrandarAlijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espacio_extra', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_skin', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BearSkinExtension',
        ),
        migrations.DeleteModel(
            name='InvExtension',
        ),
        migrations.DeleteModel(
            name='PveExtension',
        ),
        migrations.DeleteModel(
            name='UsecSkinExtension',
        ),
        migrations.RemoveField(
            model_name='version',
            name='nombre_version',
        ),
        migrations.AddField(
            model_name='version',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
