# Generated by Django 4.2.20 on 2025-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agrandaralijo_pve_skins_delete_bearskinextension_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pve',
            options={'verbose_name': 'PvE', 'verbose_name_plural': 'PvE'},
        ),
        migrations.AlterModelOptions(
            name='skins',
            options={'verbose_name': 'Skins', 'verbose_name_plural': 'Skins'},
        ),
        migrations.AddField(
            model_name='version',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='versiones/'),
        ),
    ]
