# Generated by Django 4.2.20 on 2025-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pve_options_alter_skins_options_version_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrandaralijo',
            name='espacio_extra',
        ),
        migrations.RemoveField(
            model_name='skins',
            name='tipo_skin',
        ),
        migrations.AddField(
            model_name='agrandaralijo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alijos/'),
        ),
        migrations.AddField(
            model_name='skins',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='skins/'),
        ),
        migrations.AlterField(
            model_name='agrandaralijo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agrandaralijo',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skins',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skins',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
