# Generated by Django 4.2.20 on 2025-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_agrandaralijo_espacio_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='skins',
            name='facción',
            field=models.CharField(choices=[('bear', 'BEAR'), ('usec', 'USEC')], default='BEAR', max_length=4),
        ),
    ]
