# Generated by Django 4.2.20 on 2025-05-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfilusuario_apellido_perfilusuario_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
