# Generated by Django 4.2.20 on 2025-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_perfilusuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='contrasenna',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
