# Generated by Django 4.2.20 on 2025-05-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilusuario_contrasenna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='nickname',
            new_name='username',
        ),
    ]
