# Generated by Django 4.2.20 on 2025-05-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_compra_resena_hecha_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_reseña', to='core.compra'),
        ),
    ]
